name_prefix: f5-prefix-
net:
  vlan:
    - name: ha
      tag: 100
      interfaces:
        1.3: untagged # tagged
      self:
        - name: ha-local
          ip: 10.1.1.1/29
          traffic_group: traffic-group-local-only
          services: default
    - name: frontend
      tag: 110
      interfaces:
        1.2: untagged # tagged
      self:
        - name: fe-local
          ip: 10.1.2.2/24
          traffic_group: traffic-group-local-only
          services: none
        - name: fe-floating
          ip: 10.1.2.1/24
          traffic_group: traffic-group-1
          services: none
    - name: backend
      tag: 120
      interfaces:
        1.1: untagged # tagged
      self:
        - name: be-local
          ip: 10.1.3.2/24
          traffic_group: traffic-group-local-only
          services: none
        - name: be-floating
          ip: 10.1.3.1/29
          traffic_group: traffic-group-1
          services: none
  route:
    - name: be-192.168.1.0_24
      prefix: 192.168.1.0/24
      gw: 10.1.3.254
      description: Backend route to servers
